# Numpy

In [4]:
#Numerical Python

import numpy as np

#Create a tuple and convert it as an array using array

tup=(1,2,3,4,5)
arr2= np.array(tup)      #n dimentional array from tuple

lis=[1,2,3]
arrl=np.array(lis)       #n dimentional array from a list

arr=np.array(range(1,10))          #n dimentional array from a range


#display the properties of an array
print("array: \n",arr)

print("shape: ",arr.shape)         
print("ndim: ",arr.ndim)
print("size: ",arr.size)
print("itemsize: ",arr.itemsize)
print("nbytes: ",arr.nbytes)





array: 
 [1 2 3 4 5 6 7 8 9]
shape:  (9,)
ndim:  1
size:  9
itemsize:  4
nbytes:  36


In [6]:
#specify the dimensions

tup=(1,2,3,4,5)
arr= np.array(tup,ndmin=2)      #n dimentional array
print(type(arr))

print("shape: ",arr,arr.shape)

<class 'numpy.ndarray'>
shape:  [[1 2 3 4 5]] (1, 5)


In [8]:
#Typecasting in arrays

tup=(1.1,2,3,4,5)
arr= np.array(tup,ndmin=2,dtype=float)      #n dimentional array
print(type(arr))

print("shape: ",arr,arr.shape)

<class 'numpy.ndarray'>
shape:  [[1.1 2.  3.  4.  5. ]] (1, 5)


In [33]:
# create a list with 6 elements 
#convert to array numpy datatype
#import numpy and alias as npy
# find data type
#print the values
#find the dimensions of the elements

import numpy as npy

lis=[1,2,3,4,5,6]
arr4=npy.array(lis,dtype=float,ndmin=2)

print(arr4,arr4.shape)




[[1. 2. 3. 4. 5. 6.]] (1, 6)


In [35]:
# create a data type and use it in a array
import numpy as npy

arr=npy.array(range(1,10),ndmin=2,dtype=np.str)
print(arr)
print(type(arr.nbytes))

dt=np.dtype(np.int64)
arr1=npy.array(lis,ndmin=2,dtype=dt)
print(type(arr1.nbytes))

dt=np.int64
arr2=npy.array(lis,ndmin=2,dtype=dt)
print(type(arr2.nbytes))

[['1' '2' '3' '4' '5' '6' '7' '8' '9']]
<class 'int'>
<class 'int'>
<class 'int'>


In [9]:
#practice
import numpy as np
arr=np.array(range(1,10),ndmin=3,dtype=int)
print(arr)
arr1=np.arange(10)
print(arr1)
mat=arr1.reshape(2,5)
print(mat)

[[[1 2 3 4 5 6 7 8 9]]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
#convert a list into array and then to a matrix
lis=[[1,2],[3,4]]
a=np.array(lis,ndmin=2)
b=a.reshape(2,2)
print("matrix1: ","\n",a,a.nbytes,a.shape)

print("matrix2: ","\n",b,b.nbytes,b.shape)




matrix1:  
 [[1 2]
 [3 4]] 16 (2, 2)
matrix2:  
 [[1 2]
 [3 4]] 16 (2, 2)


In [59]:
lis=[[1,2,3],[3,4,5]]
a=np.array(lis,ndmin=2)
b=a.reshape(3,2)
print("matrix1: ","\n",a,a.nbytes,a.shape)

print("matrix2: ","\n",b,b.nbytes,b.shape)


matrix1:  
 [[1 2 3]
 [3 4 5]] 24 (2, 3)
matrix2:  
 [[1 2]
 [3 3]
 [4 5]] 24 (3, 2)


In [71]:
lis=[[1,2,3],[3,4,5]]
a=np.array(lis,ndmin=2)
b=a.reshape(3,2)
print("matrix1: ","\n",a,a.nbytes,a.shape)

print("matrix2: ","\n",b,b.nbytes,b.shape)


matrix1:  
 [[1 2 3]
 [3 4 5]] 24 (2, 3)
matrix2:  
 [[1 2]
 [3 3]
 [4 5]] 24 (3, 2)


In [84]:
lis=[[1,2,3],[3,4,5],[1,2,3],[3,4,5],[1,2,3],[3,4,5],[3,4,5],[3,4,5]]
a=np.array(lis,ndmin=3)
b=a.reshape(2,3,4)
print("matrix1:\n ",a,a.nbytes,a.shape)

print("matrix2: ","\n",b,b.nbytes,b.shape)


matrix1:
  [[[1 2 3]
  [3 4 5]
  [1 2 3]
  [3 4 5]
  [1 2 3]
  [3 4 5]
  [3 4 5]
  [3 4 5]]] 96 (1, 8, 3)
matrix2:  
 [[[1 2 3 3]
  [4 5 1 2]
  [3 3 4 5]]

 [[1 2 3 3]
  [4 5 3 4]
  [5 3 4 5]]] 96 (2, 3, 4)


In [10]:
mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))

apple
banana
cherry


In [99]:
sq=np.arange(9)
print(sq)
print(sq.ndim)
print(sq.shape)
sq.astype(float)

[0 1 2 3 4 5 6 7 8]
1
(9,)


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [89]:
sq.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

# Generating random arrays 

In [98]:
array=np.arange(1,10)
print(array)
array=np.arange(1,10,2)
array

[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [9]:
array=np.linspace(15,16,num=8)
print(array)
array=np.linspace(15,16,num=8,endpoint=False)
array

[15.         15.14285714 15.28571429 15.42857143 15.57142857 15.71428571
 15.85714286 16.        ]


array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875])

In [125]:
array=np.linspace(95,98,num=20)
#convert=np.array((array*(5/9))+32)
#convert = np.array(list((map(lambda x:((x*(5/9))+32),array))))

res=array*(5/9)+32
print(res)
#convert

[84.77777778 84.86549708 84.95321637 85.04093567 85.12865497 85.21637427
 85.30409357 85.39181287 85.47953216 85.56725146 85.65497076 85.74269006
 85.83040936 85.91812865 86.00584795 86.09356725 86.18128655 86.26900585
 86.35672515 86.44444444]


In [129]:
#difference between array sequence and matrix

seq=np.linspace(1,24,num=24)
array1=np.array(seq,ndmin=3)
matrix=array1.reshape(3,2,4)
print("seq:\n",seq,"\n","array1:\n",array1,"\n","matrix:\n",matrix,"\n")


seq:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.] 
 array1:
 [[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
   18. 19. 20. 21. 22. 23. 24.]]] 
 matrix:
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]

 [[17. 18. 19. 20.]
  [21. 22. 23. 24.]]] 



In [133]:
seq=np.arange(24)
mat=seq.reshape(4,6)
mat

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [136]:
seq=np.arange(24)
mat=seq.reshape(2,4,3)
print(mat,mat.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] (2, 4, 3)


In [137]:
print(mat[1])

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [145]:
a=np.ones((4,4))
b=np.ones((4,4))
c=a+b
print(c,"\n",c.shape,"\n",c.ndim)


[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]] 
 (4, 4) 
 2


In [152]:
a=np.zeros((4,4),int)
b=np.ones((4,4),int)
print(a,b,a+b)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [158]:
seq=np.arange(24)
mat=seq.reshape(1,8,3)
print(mat)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [10]:
x= np.random.random((1,3,4))
y= np.random.random((3,3,4))
print(x,y)

[[[0.66465693 0.86142669 0.87015968 0.75643308]
  [0.28917979 0.65971924 0.15884606 0.50216498]
  [0.75024771 0.07940311 0.88861079 0.78328317]]] [[[0.38990914 0.11253924 0.1260363  0.37726845]
  [0.20155381 0.02519934 0.1736306  0.51683082]
  [0.49019239 0.03991177 0.78444038 0.53537196]]

 [[0.3775012  0.93835179 0.95874545 0.36733341]
  [0.7649889  0.28576272 0.88026356 0.85351249]
  [0.55142669 0.98239322 0.78968668 0.7182015 ]]

 [[0.70410922 0.93943548 0.1309063  0.90868865]
  [0.93873678 0.48289341 0.65611907 0.03528715]
  [0.41972101 0.44630801 0.15726966 0.20770319]]]


In [168]:
z=np.random.random((1,5,5))
z



array([[[0.44474066, 0.76551431, 0.523264  , 0.20670195, 0.76991022],
        [0.91638898, 0.95018653, 0.04436662, 0.92712218, 0.24751445],
        [0.88154332, 0.71087642, 0.13046678, 0.6615967 , 0.35661638],
        [0.00594319, 0.86147936, 0.89591698, 0.9035984 , 0.00697586],
        [0.9702367 , 0.34349855, 0.99633985, 0.67481896, 0.59359606]]])

In [12]:
a=np.random.randint(3,10,9)
print(a)
b=a.reshape(3,3)
print(b)

[3 7 3 4 6 7 6 3 5]
[[3 7 3]
 [4 6 7]
 [6 3 5]]


In [13]:
x=np.random.randint(1,100,9).reshape(3,3)
y=np.random.randint(1,100,9).reshape(3,3)
print(np.add(x,y))
print(x+y)

[[ 67  52 152]
 [136  81 178]
 [ 70  70 121]]
[[ 67  52 152]
 [136  81 178]
 [ 70  70 121]]


In [14]:
x=np.arange(2,6).reshape(2,2)
y=np.arange(5,9).reshape(2,2)
print(x,"\n",y,"\n",np.dot(x,y))

[[2 3]
 [4 5]] 
 [[5 6]
 [7 8]] 
 [[31 36]
 [55 64]]


In [15]:
x=np.arange(6).reshape(3,2)
y=np.arange(6).reshape(2,3)
print(x,"\n",y)
print("\n")
print(np.dot(x,y))
print("\n")
print(np.multiply(x,2))
print("\n")

print(np.transpose(x))


[[0 1]
 [2 3]
 [4 5]] 
 [[0 1 2]
 [3 4 5]]


[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


[[ 0  2]
 [ 4  6]
 [ 8 10]]


[[0 2 4]
 [1 3 5]]


In [16]:
x=np.arange(15)
print("min= ",np.min(a))
print("max= ",np.max(a))
print("mean= ",a.mean())
print("median= ",np.median(a))
print("std= ",np.std(a))
print("var= ",np.var(a))
print("sum= ",np.sum(a))


min=  3
max=  7
mean=  4.888888888888889
median=  5.0
std=  1.5947444549341472
var=  2.54320987654321
sum=  44


In [17]:
x=np.arange(6).reshape(3,2)
y=np.arange(6).reshape(2,3)
print(x,"\n",y)
print("\n")
print(np.dot(x,y))
print("\n")
print(np.matmul(x,y))

[[0 1]
 [2 3]
 [4 5]] 
 [[0 1 2]
 [3 4 5]]


[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


In [18]:
x=np.arange(6).reshape(3,2)
y=np.arange(6).reshape(2,3)

In [233]:
student = np.dtype([('name','S30'),('age','i8'),('marks','f8')])
a=np.array([('small',23,23),('bhanu',23,23),('bhanu',23,23),('bhanu',23,23),('bhanu',23,23)],dtype=student)
print(a['name'])

[b'small' b'bhanu' b'bhanu' b'bhanu' b'bhanu']


In [15]:
dtype1 = np.dtype([('empid','i8'),('name','S30'),('dept','S30'),('sal','f8')])
a=np.array([('5676','bhanu','eng',2300),('5678','shrav','soc',2390),('5676','venu','math',2870),('5678','bhanu','uig',2090)],dtype=dtype1)
print(a['sal'])
print(a['name'])

[2300. 2390. 2870. 2090.]
[b'bhanu' b'shrav' b'venu' b'bhanu']


In [16]:
x=np.arange(6).reshape(3,2)
y=np.arange(6).reshape(3,2)
print("x:  \n",x,"\n")
print("y:  \n",y,"\n")
print(x.flatten(),"\n")
print(np.hstack((x,y)),"\n")
print(np.vstack((x,y)),"\n")

x:  
 [[0 1]
 [2 3]
 [4 5]] 

y:  
 [[0 1]
 [2 3]
 [4 5]] 

[0 1 2 3 4 5] 

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]] 

[[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]] 



In [18]:
x=np.random.randint(1,100,16).reshape(4,4)
x

array([[26,  5, 82, 68],
       [70, 17, 26, 91],
       [35, 34, 74,  2],
       [91, 68, 17, 37]])

In [20]:
x[1:3,1:3]
a=x[0:2,0:2]
b=x[0:2,2:4]
c=x[2:4,0:2]
d=x[2:4,2:4]
print('A',a,"\n\n\n",'B',b,"\n\n\n",'C',c,"\n\n\n",'D',d)

A [[26  5]
 [70 17]] 


 B [[82 68]
 [26 91]] 


 C [[35 34]
 [91 68]] 


 D [[74  2]
 [17 37]]


In [15]:
def median(b):


    #b.sort()
    l=len(b)
    if(l%2==0):
        print("median= ",(b[(l//2)]+b[(l//2)+1])/2)
    else:
        print("median=n ",b[(l//2)+1])



b=[2,3,4,5,6,7,8]
median(b)
            

median=  5.5


In [10]:
def swap():
    global a
    global b
    
    a,b=10,20
    a,b=b,a
    print("a is :",a)
    print("b is :",b)
    
swap()
print("a is :",a)
print("b is :",b)

a is : 20
b is : 10
a is : 20
b is : 10


In [15]:
for c in range(1,36):
    for r in range(1,35):
        if (((2*c)+(r*4)) == 94) and (c+r == 35):
            print("chicken= ", c,"rabbit: ",r)
        

chicken=  23 rabbit:  12


In [1]:
import re

In [6]:
regex_pattern = r"\."
print("\n".join(re.split(regex_pattern, input())))

123.123
123
123


In [12]:
m=re.findall(r'(\w+)@(\w+)\.(\w+)','username@hackerrank.com bdbduwbd username@hackerrank.com')


m       # The entire match 


[('username', 'hackerrank', 'com'), ('username', 'hackerrank', 'com')]

In [ ]:
def cma_generatorr(low, high):
    while low <= high:
       yield low
       low += 1

in_list = [1,2,3,4]
out_list = []
for num in cmap_generator(in_list):
    out_list.append(num)

print(out_list)

In [20]:
func1 = lambda x:x*x
func2 = lambda x:x+x
arr1 = [1,2,3,4]
func3 = map(func2,(map(func1,arr1)))
print(list(func3))

[2, 8, 18, 32]


In [32]:
func1 = lambda x:x*x
func2 = lambda x:x+x
funcs = [func1,func2]
arr1 = [1,2,3,4]
def apply(f, a):
    return map(f,a)
res = arr1
for i in funcs:
    res = list(apply(i,res))
    
print(res)

[2, 8, 18, 32]


In [76]:
def func123(funcs,arr1):
    res = arr1
    for i in funcs:
        temp_func=map(i,res)
        res = list(temp_func)

    yield iter(res)

In [78]:
func1 = lambda x:x*x
func2 = lambda x:x+x
funcs = [func1,func2]
arr1 = [1,2,3,4]
for i in func123(funcs,arr1):
    print(str(i))
    

In [80]:
#pool= '80123455678981234567899'
pool= '8888885555555555558555'

x=len(re.findall(r"8+\d{10}", pool))
y=len(re.findall(r"\d{10}8", pool))
y

1

In [134]:
#Reading the data
import pandas as pd
train = pd.read_csv('https://s3.amazonaws.com/istreet-questions-us-east-1/417582/train.csv',header=None)
test = pd.read_csv('https://s3.amazonaws.com/istreet-questions-us-east-1/417582/test.csv',header=None)
#train data
X_train = train.iloc[:,:-1]
y_train = train.iloc[:,-1]
#test data
X_test = test

#Linear Regression Model
from sklearn import linear_model
lm=linear_model.LinearRegression()
lm.fit(X_train,y_train)
predictions = lm.predict(X_test)


#save the predictions
import numpy as np
np.savetxt('pred.csv', predictions)

In [135]:
print('R square is %1.3f' %lm.score(X_train,y_train))

R square is 0.998


In [143]:
corr_matrix = train.corr()
count=0
for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if (abs(corr_matrix.iloc[i, j] )<= 0.1):
            colname1 = corr_matrix.columns[i] # getting the name of column
            colname2 = corr_matrix.index[j] # getting the name of column
            if(colname1 == 501):
                print(colname1,colname2)
                print(corr_matrix.iloc[i, j])
            
#print(corr_matrix)

In [141]:
train.shape

(4000, 501)

In [155]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calculate_vif(x):
    thresh = 5.0
    output = pd.DataFrame()
    k = x.shape[1]
    vif = [variance_inflation_factor(x.values, j) for j in range(x.shape[1])]
    for i in range(1,k):
        print("Iteration no.:",i)
        print(vif)
        a = np.argmax(vif)
        print("Max VIF is for variable no.:",x.columns[a],a)
        if vif[a] <= thresh :
            break
        if i == 1 :          
            output = x.drop(x.columns[a], axis = 1)
            vif = [variance_inflation_factor(output.values, j) for j in range(output.shape[1])]
        elif i > 1 :
            output = output.drop(output.columns[a],axis = 1)
            vif = [variance_inflation_factor(output.values, j) for j in range(output.shape[1])]
    return(output)

In [156]:
df_out = calculate_vif(train)

Iteration no.: 1
[1576.7267489680512, 821.9405257097352, 119.90106124501848, 2643.9193340906954, 256.35044481041933, 190.13647893645893, 135.3606316849863, 318.05974456542964, 1088.1394369186617, 1808.7974956417831, 196.1897913079752, 409.1643985599483, 198.3555893939611, 658.4103968048295, 157.78002643399017, 226.1855052654198, 146.70748314481287, 184.6365788958778, 138.9997840646872, 205.9297656276518, 459.5351523948104, 65.45059064710046, 195.76491308721427, 280.16447485963624, 284.6823533386804, 532.9230405633579, 914.1227614151676, 527.4404819887919, 526.6928186734219, 92.24699830855363, 84.52056148060285, 1914.9331715929075, 1649.3532693674192, 493.4204517101413, 182.2446770944557, 156.36147825549492, 138.1921717321095, 47.50135373836922, 169.43237107714887, 891.0155813469725, 214.08652473443257, 902.3886441468501, 2926.549755924887, 521.9801561861224, 661.8760211508268, 101.07484444054857, 2463.233776727364, 182.17537884157167, 4652.183331568561, 3602.904720399041, 177.373479160

KeyboardInterrupt: 

In [ ]:
df_out.head(5)

In [149]:
test.shape

(1000, 500)

In [150]:
train.shape

(4000, 501)

In [3]:
import pandas as pd
from sklearn import linear_model
train = pd.read_csv('https://s3.amazonaws.com/istreet-questions-us-east-1/417582/train.csv',header=None)
test = pd.read_csv('https://s3.amazonaws.com/istreet-questions-us-east-1/417582/test.csv',header=None)

X = train.iloc[:,:-1]
y = train.iloc[:,-1]

lm=linear_model.LinearRegression()
model = lm.fit(X,y)
predictions = lm.predict(test)

pd.DataFrame(predictions).to_csv('pred.csv')

In [147]:
print('R square is %1.3f' %lm.score(X,y))

R square is 0.998


In [1]:
#Reading the data
import pandas as pd
train = pd.read_csv('https://s3.amazonaws.com/istreet-questions-us-east-1/417582/train.csv',header=None)
test = pd.read_csv('https://s3.amazonaws.com/istreet-questions-us-east-1/417582/test.csv',header=None)
#train data
X_train = train.iloc[:,:-1]
y_train = train.iloc[:,-1]
#test data
X_test = test

In [2]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100, random_state = 42)
rf.fit(X_train, y_train)
predictions = rf.predict(X_test)

In [159]:
predictions = rf.predict(X_test)

In [7]:

from itertools import combinations
comb = combinations([1,2,3,4,5],2)
for i in comb:
    print(sum(i),i)

3 (1, 2)
4 (1, 3)
5 (1, 4)
6 (1, 5)
5 (2, 3)
6 (2, 4)
7 (2, 5)
7 (3, 4)
8 (3, 5)
9 (4, 5)


In [8]:
list = list(int(input().split()))


4


TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [26]:
inp = list(input().split())
inp1 = [int(i) for i in inp]
m=inp1[0]
print(inp1[m*-1])

2 3 4 5 6 7
6


In [24]:
l1 = [2,3,4,5,6,7]
l1[3*-1]

5

In [2]:
l1 = [2,3,4,5,6,7,2]
l1.count(2)

2

In [4]:
import numpy as np
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])